# Generated by Django 3.1.1 on 2020-09-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_auto_20200907_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='recalls',
            field=models.ManyToManyField(blank=True, related_name='pet_recalls', to='site_app.Recall', verbose_name='Отзыв'),
        ),
    ]
