# Generated by Django 3.1.1 on 2020-09-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_auto_20200907_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='recalls',
        ),
    ]
