# Generated by Django 3.1.1 on 2020-09-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0007_auto_20200909_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.pet', verbose_name='Питомец'),
        ),
    ]
