# Generated by Django 3.1.1 on 2020-09-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0008_auto_20200909_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_app.comment', verbose_name='Комментарий'),
        ),
    ]
